# Generated by Django 5.1.7 on 2025-03-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_notacalendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoYouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
